name: Pull CSV updates

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/20 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Pull latest updates
        run: |
          git pull origin main
          
      # Add steps to deploy the app, reload data, or trigger Streamlit refresh if needed
